name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

